Merge RK schemes into pecos-dev
pecos-hybrid/SU2 pull request #6
Opened 2017-10-25 17:54 UTC by trevilo

This code adds three Runge-Kutta time marching schemes for use with the flow equations.  So, it addresses issue #4.

2017-10-25 19:17 UTC, clarkpede commented
So why is the euler channel RK case failing? Is it expected to fail?

2017-10-25 20:12 UTC, trevilo commented
The euler channel RK case expected results changed b/c I changed the RK scheme it is testing.  The old RK implementation only supported a very limited version of RK and the coefficients used led to a 1st order accurate method.  The new implementation is much more general and the test now uses a higher-order accurate scheme (classic RK4).  We could have it use the old scheme, but I don't really see the point.

Anyway, I had updated the results in the parallel version of the tests but forgot the serial.  97f532d fixes the expected results in the serial version as well.

2017-10-25 20:46 UTC, clarkpede commented
I guessed that it was something like that.  I just wanted to make sure.

Were you planning to support multigrid with these three RK schemes? Or is that not implemented?

2017-10-25 20:59 UTC, trevilo commented
No multigrid support at the moment for the IMEX schemes b/c they `assert(config->GetUnsteady_Simulation() == TIME_STEPPING)` and multigrid is disabled in this mode.

In theory, the explicit RK implementation supports multigrid.  The euler/channel regression test uses it, so it at least runs.  I've confirmed that if I use RK coefficients to reproduce the old 3 stage, 1st order scheme, I get the same results from before, and the new RK4 results are similar.  So, as far as I can tell, it is working, but this has not been extensively investigated.

2017-10-26 15:57 UTC, clarkpede commented
I just pushed two changes:

1. I disabled the parallel AD tests temporarily.  They were taking too long to compile and maxing out the time limit for CI tests. I believe getting no results is better than a false negative, especially since serial AD is still working.
2.  I also removed some unused variables.

I've got some other feedback too:

+ The config file in the project root, `config_template_basic.cfg`, should be updated with the new settings.  It still has the old `RK_ALPHA_COEFF`
+ I noticed that if you turn on any of the RK schemes, you _must_ specify the number of steps and the coefficients.  Otherwise, it defaults to 0 RK steps and no coefficients. This seems like a bad idea from both a usability and an error-prevention standpoint.  If none of the options are specified (`N_RK_STEP`, `RK_AMAT_LOWER`, etc.) then I believe the program should default to a set of hardcoded values. This makes the new RK schemes easier to use, since you don't have to specify the coefficients every time.  Using the hardcoded values also prevents errors, since you don't have to worry about accidentally putting in the wrong coefficients when all you want are the standard values.
+ I also tried running a steady-state problem with multigrid and explicit RK.  I got a segfault while it was calculating the first step.  We don't need steady-state to work with multigrid and explicit RK, so we could just fence off that possibility.

2017-10-27 13:45 UTC, trevilo commented
Thanks Clark.  Regarding the template config file, yes, I agree.  For the defaults, yeah, that makes sense.  I'll make these fixes asap.

Can you give details on the case you're running that seg faults?  I don't mind making steady-state+multigrid+RK illegal since we're not going to use it.  But, I'm surprised it is seg faulting b/c this option is used by the euler/channel regression test, which runs fine.

2017-10-27 15:07 UTC, clarkpede commented
I used the flat plate boundary layer case with the SA model. I attached a grid and config file that give you the error.

I discovered that the segfault disappears if you switch the flow numerics from `2ND_ORDER` to `2ND_ORDER_LIMITER`. That explains why the euler channel regression test isn't failing.

rk-mgrid-segfault.tar.gz](https://github.com/pecos-hybrid/SU2/files/1422475/rk-mgrid-segfault.tar.gz)

2017-10-27 15:10 UTC, clarkpede requested changes

2017-10-27 15:10 UTC, clarkpede commented on SU2_CFD/src/solver_direct_mean.cpp
> +  // TODO: Let user set these through the input file
Are we planning on letting the user input these? Or do we want to keep them hardcoded?

2017-10-27 15:10 UTC, clarkpede commented on SU2_CFD/src/solver_direct_mean.cpp
> +  dt = node[0]->GetDelta_Time();
This is a bit hacky.  The proper way of doing this would be to pull the Delta_Time from config, but SU2 doesn't update config with the unsteady time for `TIME_STEPPING`.  We should fix the problems with time-stepping, then come back and change this.

2017-10-27 15:10 UTC, clarkpede commented on TestCases/fea_fsi/DynBeam_2d/configBeam_2d.cfg
> +NEWMA
Was this an intentional change?

2017-10-27 15:10 UTC, clarkpede commented on TestCases/harmonic_balance/HB.cfg
> +
We should remove these empty lines from the test files.
EDIT: And the blank line with `%` above or below as well (so we don't end up with two `%` rows)

2017-10-27 15:10 UTC, clarkpede commented on SU2_CFD/src/solver_direct_mean.cpp
> +  // FIXME: Not currently updating time!  Do it!
What's the status on this FIXME? Does it need to be resolved, or are we fine leaving it how it is?

2017-10-27 15:10 UTC, clarkpede commented on SU2_CFD/src/solver_direct_mean.cpp
> +  const bool final_step = (iRKStep+1 == nRKStep);
`final_step` isn't used.  Should we be using it to do something different the last step? Or should it be deleted?

2017-10-27 15:10 UTC, clarkpede commented on Common/src/config_structure.cpp
> +          cout << "  Amat = " << endl;
I propose changing these "Amat", "bVec" printouts to more readable "A matrix:", "b Vector", etc.  What do you think?

2017-10-27 15:10 UTC, clarkpede commented on Common/src/config_structure.cpp
> +          cout << "]" << endl;
You're missing `RUNGE_KUTTA_LIMEX_SMR91` from this switch/case.  Was that intentional?

2017-10-27 17:31 UTC, trevilo commented
Hey Clark, thanks for the comments.  I'll address asap.

In the meantime, a9c18ca ought to fix the seg fault you observed.  There was a spot in the Roe upwind flux calc where the Jacobian was being set regardless of whether running implicit or explicit in time.  It was only accessed when a non-physical condition was encountered, which explains the differences observed for different test cases and spatial schemes.

2017-11-01 02:35 UTC, trevilo commented on Common/src/config_structure.cpp
> +          cout << "]" << endl;
Fixed in 
434e685

2017-11-01 02:35 UTC, trevilo commented on Common/src/config_structure.cpp
> +          cout << "  Amat = " << endl;
Fixed in 
e20ff97

2017-11-01 02:37 UTC, trevilo commented on TestCases/fea_fsi/DynBeam_2d/configBeam_2d.cfg
> +NEWMA
Nope... a result of my sed script matching on RK_ALPHA.  Doh.  Good catch.  Fixed in 
8a9f4a5

2017-11-01 02:38 UTC, trevilo commented on TestCases/harmonic_balance/HB.cfg
> +
White space clean up in 
3c520f1 and 42aa125

2017-11-01 02:40 UTC, trevilo commented on SU2_CFD/src/solver_direct_mean.cpp
> +  // FIXME: Not currently updating time!  Do it!
I vote we leave it for now as it is not yet blocking anything.

2017-11-01 02:41 UTC, trevilo commented on SU2_CFD/src/solver_direct_mean.cpp
> +  // TODO: Let user set these through the input file
Eventually, yes.  For now I vote we leave it as it isn't blocking anything.

2017-11-01 02:44 UTC, trevilo commented on SU2_CFD/src/solver_direct_mean.cpp
> +  dt = node[0]->GetDelta_Time();
yeah, I agree it is a bit ugly.  But, works fine for now.  I don't see much motivation to change it until we do a bigger clean up of how time and dt are handled for time stepping.

2017-11-01 13:00 UTC, clarkpede approved these changes

2017-11-01 19:02 UTC, merged